name: borrowarr-client

services:
  borrowarr-client:
    container_name: borrowarr-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3012:3012'
    environment:
      - NODE_ENV=production
      - PORT=3012
      - NEXT_PUBLIC_API_URL=https://api.codereader.app
    restart: unless-stopped