name: borrowarr-server

services:
  borrowarr-server:
    restart: unless-stopped
    build: .
    container_name: borrowarr-server
    ports:
      - "3013:3013"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    stdin_open: true  # This allows interactive commands (optional)
    tty: true         # This allows for TTY (optional)
    command: npm run dev